[tool.poetry]
name = "openbb-agents"
version = "0.1.0"
description = "LLMs X OpenBB"
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11,<3.12"
jupyterlab = "^4.0.9"
langchain = "^0.0.340"
openbb = "4.0.1"
openai = "^1.3.5"
sentence-transformers = "^2.2.2"
tiktoken = "^0.5.1"
faiss-cpu = "^1.7.4"
langchainhub = "^0.1.14"
python-json-logger = "^2.0.7"
fastapi = "^0.104.1"
uvicorn = "^0.24.0"
argparse = "^1.4.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
